services:
  tree-sitter-tcl:
    build:
      context: .
      dockerfile: Dockerfile
    image: tree-sitter-tcl:dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["bash"]
