#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 5

enum {
  sym_simple_word = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  sym_comment = 4,
  anon_sym_DOLLAR = 5,
  aux_sym__simple_variable_token1 = 6,
  anon_sym_DOLLAR_LBRACE = 7,
  aux_sym__braced_variable_token1 = 8,
  anon_sym_RBRACE = 9,
  anon_sym_LBRACE = 10,
  anon_sym_set = 11,
  anon_sym_proc = 12,
  anon_sym_elseif = 13,
  anon_sym_else = 14,
  anon_sym_if = 15,
  anon_sym_DQUOTE = 16,
  sym_escaped_character = 17,
  sym__quoted_word_content = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  sym_source_file = 21,
  sym_commands = 22,
  aux_sym__commands = 23,
  sym__command = 24,
  sym_command = 25,
  sym_word_list = 26,
  sym__word = 27,
  sym_variable_substitution = 28,
  sym__simple_variable = 29,
  sym__braced_variable = 30,
  sym_command_block = 31,
  sym_set = 32,
  sym_procedure = 33,
  sym_procedure_arguments = 34,
  sym_elseif = 35,
  sym_else = 36,
  sym_conditional = 37,
  sym_quoted_word = 38,
  sym_braced_word = 39,
  sym_command_substitution = 40,
  aux_sym_word_list_repeat1 = 41,
  aux_sym_procedure_arguments_repeat1 = 42,
  aux_sym_conditional_repeat1 = 43,
  aux_sym_quoted_word_repeat1 = 44,
  aux_sym_braced_word_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_simple_word] = "simple_word",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [anon_sym_DOLLAR] = "$",
  [aux_sym__simple_variable_token1] = "_simple_variable_token1",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym__braced_variable_token1] = "_braced_variable_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE] = "{",
  [anon_sym_set] = "set",
  [anon_sym_proc] = "proc",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [anon_sym_if] = "if",
  [anon_sym_DQUOTE] = "\"",
  [sym_escaped_character] = "escaped_character",
  [sym__quoted_word_content] = "_quoted_word_content",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_commands] = "commands",
  [aux_sym__commands] = "_commands",
  [sym__command] = "_command",
  [sym_command] = "command",
  [sym_word_list] = "word_list",
  [sym__word] = "_word",
  [sym_variable_substitution] = "variable_substitution",
  [sym__simple_variable] = "_simple_variable",
  [sym__braced_variable] = "_braced_variable",
  [sym_command_block] = "command_block",
  [sym_set] = "set",
  [sym_procedure] = "procedure",
  [sym_procedure_arguments] = "procedure_arguments",
  [sym_elseif] = "elseif",
  [sym_else] = "else",
  [sym_conditional] = "conditional",
  [sym_quoted_word] = "quoted_word",
  [sym_braced_word] = "braced_word",
  [sym_command_substitution] = "command_substitution",
  [aux_sym_word_list_repeat1] = "word_list_repeat1",
  [aux_sym_procedure_arguments_repeat1] = "procedure_arguments_repeat1",
  [aux_sym_conditional_repeat1] = "conditional_repeat1",
  [aux_sym_quoted_word_repeat1] = "quoted_word_repeat1",
  [aux_sym_braced_word_repeat1] = "braced_word_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_simple_word] = sym_simple_word,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym__simple_variable_token1] = aux_sym__simple_variable_token1,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym__braced_variable_token1] = aux_sym__braced_variable_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_proc] = anon_sym_proc,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_escaped_character] = sym_escaped_character,
  [sym__quoted_word_content] = sym__quoted_word_content,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_commands] = sym_commands,
  [aux_sym__commands] = aux_sym__commands,
  [sym__command] = sym__command,
  [sym_command] = sym_command,
  [sym_word_list] = sym_word_list,
  [sym__word] = sym__word,
  [sym_variable_substitution] = sym_variable_substitution,
  [sym__simple_variable] = sym__simple_variable,
  [sym__braced_variable] = sym__braced_variable,
  [sym_command_block] = sym_command_block,
  [sym_set] = sym_set,
  [sym_procedure] = sym_procedure,
  [sym_procedure_arguments] = sym_procedure_arguments,
  [sym_elseif] = sym_elseif,
  [sym_else] = sym_else,
  [sym_conditional] = sym_conditional,
  [sym_quoted_word] = sym_quoted_word,
  [sym_braced_word] = sym_braced_word,
  [sym_command_substitution] = sym_command_substitution,
  [aux_sym_word_list_repeat1] = aux_sym_word_list_repeat1,
  [aux_sym_procedure_arguments_repeat1] = aux_sym_procedure_arguments_repeat1,
  [aux_sym_conditional_repeat1] = aux_sym_conditional_repeat1,
  [aux_sym_quoted_word_repeat1] = aux_sym_quoted_word_repeat1,
  [aux_sym_braced_word_repeat1] = aux_sym_braced_word_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_simple_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__simple_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__braced_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_proc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_escaped_character] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_word_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_commands] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__commands] = {
    .visible = false,
    .named = false,
  },
  [sym__command] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_word_list] = {
    .visible = true,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_variable] = {
    .visible = false,
    .named = true,
  },
  [sym__braced_variable] = {
    .visible = false,
    .named = true,
  },
  [sym_command_block] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif] = {
    .visible = true,
    .named = true,
  },
  [sym_else] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_word] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_word] = {
    .visible = true,
    .named = true,
  },
  [sym_command_substitution] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_word_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_procedure_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conditional_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_word_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_body = 2,
  field_condition = 3,
  field_name = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_arguments, 1},
    {field_name, 0},
  [3] =
    {field_condition, 1},
  [4] =
    {field_arguments, 2},
    {field_body, 3},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 5,
  [8] = 8,
  [9] = 3,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 15,
  [16] = 11,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 18,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 32,
  [40] = 34,
  [41] = 36,
  [42] = 31,
  [43] = 30,
  [44] = 34,
  [45] = 33,
  [46] = 46,
  [47] = 32,
  [48] = 33,
  [49] = 35,
  [50] = 30,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 60,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 73,
  [75] = 75,
  [76] = 76,
  [77] = 75,
  [78] = 76,
  [79] = 73,
  [80] = 75,
  [81] = 76,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 82,
  [86] = 82,
};

static inline bool sym_comment_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || c == '"'))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym_simple_word_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '"'
        ? c == ' '
        : c <= '"')))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__simple_variable_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__braced_variable_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym__braced_variable_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_escaped_character);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_simple_word);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_simple_word);
      if (!sym_simple_word_character_set_1(lookahead)) ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'p') ADVANCE(3);
      if (lookahead == 's') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'f') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_proc);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 8},
  [71] = {.lex_state = 8},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_simple_word] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_proc] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escaped_character] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(84),
    [aux_sym__commands] = STATE(8),
    [sym__command] = STATE(64),
    [sym_command] = STATE(64),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(64),
    [sym_procedure] = STATE(64),
    [sym_conditional] = STATE(64),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_proc] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [2] = {
    [aux_sym__commands] = STATE(3),
    [sym__command] = STATE(60),
    [sym_command] = STATE(60),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(60),
    [sym_procedure] = STATE(60),
    [sym_conditional] = STATE(60),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(29),
    [sym_comment] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_proc] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(33),
  },
  [3] = {
    [aux_sym__commands] = STATE(3),
    [sym__command] = STATE(60),
    [sym_command] = STATE(60),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(60),
    [sym_procedure] = STATE(60),
    [sym_conditional] = STATE(60),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [sym_simple_word] = ACTIONS(35),
    [anon_sym_LF] = ACTIONS(38),
    [anon_sym_SEMI] = ACTIONS(41),
    [sym_comment] = ACTIONS(44),
    [anon_sym_DOLLAR] = ACTIONS(47),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_set] = ACTIONS(58),
    [anon_sym_proc] = ACTIONS(61),
    [anon_sym_if] = ACTIONS(64),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_LBRACK] = ACTIONS(70),
    [anon_sym_RBRACK] = ACTIONS(53),
  },
  [4] = {
    [sym_commands] = STATE(83),
    [aux_sym__commands] = STATE(2),
    [sym__command] = STATE(60),
    [sym_command] = STATE(60),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(60),
    [sym_procedure] = STATE(60),
    [sym_conditional] = STATE(60),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(73),
    [anon_sym_SEMI] = ACTIONS(75),
    [sym_comment] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_proc] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [5] = {
    [sym_commands] = STATE(81),
    [aux_sym__commands] = STATE(2),
    [sym__command] = STATE(60),
    [sym_command] = STATE(60),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(60),
    [sym_procedure] = STATE(60),
    [sym_conditional] = STATE(60),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(73),
    [anon_sym_SEMI] = ACTIONS(75),
    [sym_comment] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_proc] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [6] = {
    [sym_commands] = STATE(78),
    [aux_sym__commands] = STATE(2),
    [sym__command] = STATE(60),
    [sym_command] = STATE(60),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(60),
    [sym_procedure] = STATE(60),
    [sym_conditional] = STATE(60),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(73),
    [anon_sym_SEMI] = ACTIONS(75),
    [sym_comment] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_proc] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [7] = {
    [sym_commands] = STATE(76),
    [aux_sym__commands] = STATE(2),
    [sym__command] = STATE(60),
    [sym_command] = STATE(60),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(60),
    [sym_procedure] = STATE(60),
    [sym_conditional] = STATE(60),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(73),
    [anon_sym_SEMI] = ACTIONS(75),
    [sym_comment] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_proc] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [8] = {
    [aux_sym__commands] = STATE(9),
    [sym__command] = STATE(64),
    [sym_command] = STATE(64),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(64),
    [sym_procedure] = STATE(64),
    [sym_conditional] = STATE(64),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(81),
    [anon_sym_SEMI] = ACTIONS(83),
    [sym_comment] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_proc] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [9] = {
    [aux_sym__commands] = STATE(9),
    [sym__command] = STATE(64),
    [sym_command] = STATE(64),
    [sym__word] = STATE(10),
    [sym_variable_substitution] = STATE(10),
    [sym__simple_variable] = STATE(32),
    [sym__braced_variable] = STATE(32),
    [sym_set] = STATE(64),
    [sym_procedure] = STATE(64),
    [sym_conditional] = STATE(64),
    [sym_quoted_word] = STATE(10),
    [sym_braced_word] = STATE(10),
    [sym_command_substitution] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_simple_word] = ACTIONS(35),
    [anon_sym_LF] = ACTIONS(87),
    [anon_sym_SEMI] = ACTIONS(90),
    [sym_comment] = ACTIONS(93),
    [anon_sym_DOLLAR] = ACTIONS(47),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_set] = ACTIONS(58),
    [anon_sym_proc] = ACTIONS(61),
    [anon_sym_if] = ACTIONS(64),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_LBRACK] = ACTIONS(70),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      sym_simple_word,
    ACTIONS(98), 1,
      anon_sym_LF,
    ACTIONS(100), 1,
      anon_sym_SEMI,
    STATE(59), 1,
      sym_word_list,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(13), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [40] = 10,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(102), 1,
      sym_simple_word,
    ACTIONS(104), 1,
      anon_sym_LF,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(17), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [77] = 10,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      sym_simple_word,
    ACTIONS(110), 1,
      anon_sym_LF,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(11), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [114] = 10,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(114), 1,
      sym_simple_word,
    ACTIONS(116), 1,
      anon_sym_LF,
    ACTIONS(118), 1,
      anon_sym_SEMI,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(15), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [151] = 10,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(120), 1,
      sym_simple_word,
    ACTIONS(122), 1,
      anon_sym_LF,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(16), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [188] = 10,
    ACTIONS(126), 1,
      sym_simple_word,
    ACTIONS(129), 1,
      anon_sym_LF,
    ACTIONS(131), 1,
      anon_sym_SEMI,
    ACTIONS(133), 1,
      anon_sym_DOLLAR,
    ACTIONS(136), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(139), 1,
      anon_sym_LBRACE,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      anon_sym_LBRACK,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(15), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [225] = 10,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(102), 1,
      sym_simple_word,
    ACTIONS(104), 1,
      anon_sym_LF,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(17), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [262] = 10,
    ACTIONS(150), 1,
      sym_simple_word,
    ACTIONS(153), 1,
      anon_sym_LF,
    ACTIONS(156), 1,
      anon_sym_DOLLAR,
    ACTIONS(159), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      anon_sym_LBRACK,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(17), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [299] = 2,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(53), 13,
      anon_sym_SEMI,
      sym_comment,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_set,
      anon_sym_proc,
      anon_sym_if,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [318] = 8,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(173), 1,
      sym_simple_word,
    ACTIONS(175), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      anon_sym_LBRACK,
    STATE(32), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(70), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [348] = 8,
    ACTIONS(183), 1,
      sym_simple_word,
    ACTIONS(185), 1,
      anon_sym_DOLLAR,
    ACTIONS(187), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(189), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(19), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [378] = 8,
    ACTIONS(185), 1,
      anon_sym_DOLLAR,
    ACTIONS(187), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(189), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    ACTIONS(195), 1,
      sym_simple_word,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(63), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [408] = 2,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(53), 11,
      anon_sym_SEMI,
      sym_comment,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_set,
      anon_sym_proc,
      anon_sym_if,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [426] = 8,
    ACTIONS(185), 1,
      anon_sym_DOLLAR,
    ACTIONS(187), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(189), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    ACTIONS(197), 1,
      sym_simple_word,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(72), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [456] = 8,
    ACTIONS(185), 1,
      anon_sym_DOLLAR,
    ACTIONS(187), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(189), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    ACTIONS(199), 1,
      sym_simple_word,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(54), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [486] = 8,
    ACTIONS(201), 1,
      anon_sym_DOLLAR,
    ACTIONS(203), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    ACTIONS(207), 1,
      sym_escaped_character,
    ACTIONS(209), 1,
      sym__quoted_word_content,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    STATE(39), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(26), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [514] = 8,
    ACTIONS(213), 1,
      anon_sym_DOLLAR,
    ACTIONS(216), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
    ACTIONS(221), 1,
      sym_escaped_character,
    ACTIONS(224), 1,
      sym__quoted_word_content,
    ACTIONS(227), 1,
      anon_sym_LBRACK,
    STATE(39), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(26), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [542] = 8,
    ACTIONS(201), 1,
      anon_sym_DOLLAR,
    ACTIONS(203), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(207), 1,
      sym_escaped_character,
    ACTIONS(209), 1,
      sym__quoted_word_content,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    STATE(39), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(26), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [570] = 7,
    ACTIONS(201), 1,
      anon_sym_DOLLAR,
    ACTIONS(203), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(232), 1,
      sym_escaped_character,
    ACTIONS(234), 1,
      sym__quoted_word_content,
    STATE(39), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(25), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [595] = 7,
    ACTIONS(201), 1,
      anon_sym_DOLLAR,
    ACTIONS(203), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(236), 1,
      sym_escaped_character,
    ACTIONS(238), 1,
      sym__quoted_word_content,
    STATE(39), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(27), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [620] = 2,
    ACTIONS(242), 1,
      anon_sym_LF,
    ACTIONS(240), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [634] = 2,
    ACTIONS(246), 1,
      anon_sym_LF,
    ACTIONS(244), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [648] = 2,
    ACTIONS(250), 1,
      anon_sym_LF,
    ACTIONS(248), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [662] = 2,
    ACTIONS(254), 1,
      anon_sym_LF,
    ACTIONS(252), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [676] = 2,
    ACTIONS(258), 1,
      anon_sym_LF,
    ACTIONS(256), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [690] = 2,
    ACTIONS(262), 1,
      anon_sym_LF,
    ACTIONS(260), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [704] = 2,
    ACTIONS(266), 1,
      anon_sym_LF,
    ACTIONS(264), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [718] = 6,
    ACTIONS(268), 1,
      anon_sym_LF,
    ACTIONS(270), 1,
      anon_sym_SEMI,
    ACTIONS(272), 1,
      anon_sym_elseif,
    ACTIONS(274), 1,
      anon_sym_else,
    STATE(65), 1,
      sym_else,
    STATE(46), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [738] = 6,
    ACTIONS(272), 1,
      anon_sym_elseif,
    ACTIONS(274), 1,
      anon_sym_else,
    ACTIONS(276), 1,
      anon_sym_LF,
    ACTIONS(278), 1,
      anon_sym_SEMI,
    STATE(67), 1,
      sym_else,
    STATE(37), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [758] = 2,
    ACTIONS(250), 1,
      sym__quoted_word_content,
    ACTIONS(248), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [769] = 2,
    ACTIONS(258), 1,
      sym__quoted_word_content,
    ACTIONS(256), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [780] = 2,
    ACTIONS(264), 1,
      anon_sym_DOLLAR,
    ACTIONS(266), 5,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [791] = 2,
    ACTIONS(244), 1,
      anon_sym_DOLLAR,
    ACTIONS(246), 5,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [802] = 2,
    ACTIONS(240), 1,
      anon_sym_DOLLAR,
    ACTIONS(242), 5,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [813] = 2,
    ACTIONS(256), 1,
      anon_sym_DOLLAR,
    ACTIONS(258), 5,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [824] = 2,
    ACTIONS(254), 1,
      sym__quoted_word_content,
    ACTIONS(252), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [835] = 4,
    ACTIONS(280), 1,
      anon_sym_LF,
    ACTIONS(284), 1,
      anon_sym_elseif,
    ACTIONS(282), 2,
      anon_sym_SEMI,
      anon_sym_else,
    STATE(46), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [850] = 2,
    ACTIONS(248), 1,
      anon_sym_DOLLAR,
    ACTIONS(250), 5,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [861] = 2,
    ACTIONS(252), 1,
      anon_sym_DOLLAR,
    ACTIONS(254), 5,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [872] = 2,
    ACTIONS(260), 1,
      anon_sym_DOLLAR,
    ACTIONS(262), 5,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [883] = 2,
    ACTIONS(242), 1,
      sym__quoted_word_content,
    ACTIONS(240), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [894] = 2,
    ACTIONS(287), 1,
      anon_sym_LF,
    ACTIONS(289), 3,
      anon_sym_SEMI,
      anon_sym_elseif,
      anon_sym_else,
  [903] = 2,
    ACTIONS(291), 1,
      anon_sym_LF,
    ACTIONS(293), 3,
      anon_sym_SEMI,
      anon_sym_elseif,
      anon_sym_else,
  [912] = 2,
    ACTIONS(295), 1,
      anon_sym_LF,
    ACTIONS(297), 3,
      anon_sym_SEMI,
      anon_sym_elseif,
      anon_sym_else,
  [921] = 3,
    ACTIONS(299), 1,
      sym_simple_word,
    ACTIONS(301), 1,
      anon_sym_LBRACE,
    STATE(57), 1,
      sym_procedure_arguments,
  [931] = 3,
    ACTIONS(303), 1,
      sym_simple_word,
    ACTIONS(306), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_procedure_arguments_repeat1,
  [941] = 3,
    ACTIONS(308), 1,
      sym_simple_word,
    ACTIONS(310), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_procedure_arguments_repeat1,
  [951] = 3,
    ACTIONS(312), 1,
      sym_simple_word,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(62), 1,
      sym_command_block,
  [961] = 3,
    ACTIONS(316), 1,
      sym_simple_word,
    ACTIONS(318), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym_procedure_arguments_repeat1,
  [971] = 2,
    ACTIONS(320), 1,
      anon_sym_LF,
    ACTIONS(322), 1,
      anon_sym_SEMI,
  [978] = 2,
    ACTIONS(324), 1,
      anon_sym_LF,
    ACTIONS(326), 1,
      anon_sym_SEMI,
  [985] = 1,
    ACTIONS(328), 2,
      anon_sym_LBRACE,
      sym_simple_word,
  [990] = 2,
    ACTIONS(330), 1,
      anon_sym_LF,
    ACTIONS(332), 1,
      anon_sym_SEMI,
  [997] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_command_block,
  [1004] = 2,
    ACTIONS(334), 1,
      anon_sym_LF,
    ACTIONS(336), 1,
      anon_sym_SEMI,
  [1011] = 2,
    ACTIONS(338), 1,
      anon_sym_LF,
    ACTIONS(340), 1,
      anon_sym_SEMI,
  [1018] = 1,
    ACTIONS(342), 2,
      anon_sym_LBRACE,
      sym_simple_word,
  [1023] = 2,
    ACTIONS(268), 1,
      anon_sym_LF,
    ACTIONS(270), 1,
      anon_sym_SEMI,
  [1030] = 1,
    ACTIONS(344), 2,
      anon_sym_LBRACE,
      sym_simple_word,
  [1035] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_command_block,
  [1042] = 2,
    ACTIONS(346), 1,
      anon_sym_LF,
    ACTIONS(348), 1,
      anon_sym_SEMI,
  [1049] = 2,
    ACTIONS(350), 1,
      anon_sym_LF,
    ACTIONS(352), 1,
      anon_sym_SEMI,
  [1056] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_command_block,
  [1063] = 1,
    ACTIONS(354), 1,
      aux_sym__simple_variable_token1,
  [1067] = 1,
    ACTIONS(356), 1,
      aux_sym__simple_variable_token1,
  [1071] = 1,
    ACTIONS(358), 1,
      anon_sym_RBRACE,
  [1075] = 1,
    ACTIONS(360), 1,
      anon_sym_RBRACK,
  [1079] = 1,
    ACTIONS(362), 1,
      anon_sym_RBRACE,
  [1083] = 1,
    ACTIONS(364), 1,
      anon_sym_RBRACK,
  [1087] = 1,
    ACTIONS(366), 1,
      aux_sym__simple_variable_token1,
  [1091] = 1,
    ACTIONS(368), 1,
      anon_sym_RBRACE,
  [1095] = 1,
    ACTIONS(370), 1,
      anon_sym_RBRACK,
  [1099] = 1,
    ACTIONS(372), 1,
      aux_sym__braced_variable_token1,
  [1103] = 1,
    ACTIONS(374), 1,
      anon_sym_RBRACE,
  [1107] = 1,
    ACTIONS(376), 1,
      ts_builtin_sym_end,
  [1111] = 1,
    ACTIONS(378), 1,
      aux_sym__braced_variable_token1,
  [1115] = 1,
    ACTIONS(380), 1,
      aux_sym__braced_variable_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 40,
  [SMALL_STATE(12)] = 77,
  [SMALL_STATE(13)] = 114,
  [SMALL_STATE(14)] = 151,
  [SMALL_STATE(15)] = 188,
  [SMALL_STATE(16)] = 225,
  [SMALL_STATE(17)] = 262,
  [SMALL_STATE(18)] = 299,
  [SMALL_STATE(19)] = 318,
  [SMALL_STATE(20)] = 348,
  [SMALL_STATE(21)] = 378,
  [SMALL_STATE(22)] = 408,
  [SMALL_STATE(23)] = 426,
  [SMALL_STATE(24)] = 456,
  [SMALL_STATE(25)] = 486,
  [SMALL_STATE(26)] = 514,
  [SMALL_STATE(27)] = 542,
  [SMALL_STATE(28)] = 570,
  [SMALL_STATE(29)] = 595,
  [SMALL_STATE(30)] = 620,
  [SMALL_STATE(31)] = 634,
  [SMALL_STATE(32)] = 648,
  [SMALL_STATE(33)] = 662,
  [SMALL_STATE(34)] = 676,
  [SMALL_STATE(35)] = 690,
  [SMALL_STATE(36)] = 704,
  [SMALL_STATE(37)] = 718,
  [SMALL_STATE(38)] = 738,
  [SMALL_STATE(39)] = 758,
  [SMALL_STATE(40)] = 769,
  [SMALL_STATE(41)] = 780,
  [SMALL_STATE(42)] = 791,
  [SMALL_STATE(43)] = 802,
  [SMALL_STATE(44)] = 813,
  [SMALL_STATE(45)] = 824,
  [SMALL_STATE(46)] = 835,
  [SMALL_STATE(47)] = 850,
  [SMALL_STATE(48)] = 861,
  [SMALL_STATE(49)] = 872,
  [SMALL_STATE(50)] = 883,
  [SMALL_STATE(51)] = 894,
  [SMALL_STATE(52)] = 903,
  [SMALL_STATE(53)] = 912,
  [SMALL_STATE(54)] = 921,
  [SMALL_STATE(55)] = 931,
  [SMALL_STATE(56)] = 941,
  [SMALL_STATE(57)] = 951,
  [SMALL_STATE(58)] = 961,
  [SMALL_STATE(59)] = 971,
  [SMALL_STATE(60)] = 978,
  [SMALL_STATE(61)] = 985,
  [SMALL_STATE(62)] = 990,
  [SMALL_STATE(63)] = 997,
  [SMALL_STATE(64)] = 1004,
  [SMALL_STATE(65)] = 1011,
  [SMALL_STATE(66)] = 1018,
  [SMALL_STATE(67)] = 1023,
  [SMALL_STATE(68)] = 1030,
  [SMALL_STATE(69)] = 1035,
  [SMALL_STATE(70)] = 1042,
  [SMALL_STATE(71)] = 1049,
  [SMALL_STATE(72)] = 1056,
  [SMALL_STATE(73)] = 1063,
  [SMALL_STATE(74)] = 1067,
  [SMALL_STATE(75)] = 1071,
  [SMALL_STATE(76)] = 1075,
  [SMALL_STATE(77)] = 1079,
  [SMALL_STATE(78)] = 1083,
  [SMALL_STATE(79)] = 1087,
  [SMALL_STATE(80)] = 1091,
  [SMALL_STATE(81)] = 1095,
  [SMALL_STATE(82)] = 1099,
  [SMALL_STATE(83)] = 1103,
  [SMALL_STATE(84)] = 1107,
  [SMALL_STATE(85)] = 1111,
  [SMALL_STATE(86)] = 1115,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commands, 1),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(10),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(3),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(60),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(74),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(86),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__commands, 2),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(12),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(20),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(24),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(23),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(29),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(7),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__commands, 2),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(9),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(9),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(64),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, .production_id = 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, .production_id = 1),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_list, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word_list, 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(15),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(74),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(86),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(12),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(29),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(7),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(17),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(17),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(74),
  [159] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(86),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(12),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(29),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(7),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(79),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(85),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2),
  [221] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(26),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(26),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(5),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__braced_variable, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__braced_variable, 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 3),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_substitution, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_substitution, 1),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_variable, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_variable, 2),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 3),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 3),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 2),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 2),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_word, 3),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_word, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 4, .production_id = 3),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 4, .production_id = 3),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 3, .production_id = 3),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 3, .production_id = 3),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conditional_repeat1, 2),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conditional_repeat1, 2),
  [284] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conditional_repeat1, 2), SHIFT_REPEAT(21),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_block, 2),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_block, 2),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_block, 3),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_block, 3),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elseif, 3, .production_id = 3),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif, 3, .production_id = 3),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_procedure_arguments_repeat1, 2), SHIFT_REPEAT(55),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_procedure_arguments_repeat1, 2),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, .production_id = 2),
  [322] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, .production_id = 2),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [326] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_arguments, 3),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 4, .production_id = 4),
  [332] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure, 4, .production_id = 4),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [336] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 5, .production_id = 3),
  [340] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 5, .production_id = 3),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_arguments, 2),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_arguments, 1),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3),
  [348] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else, 2),
  [352] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else, 2),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [376] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tcl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_simple_word,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
