#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 5

enum {
  sym_simple_word = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  sym_comment = 4,
  anon_sym_namespace = 5,
  anon_sym_eval = 6,
  anon_sym_DOLLAR = 7,
  aux_sym__simple_variable_token1 = 8,
  anon_sym_DOLLAR_LBRACE = 9,
  aux_sym__braced_variable_token1 = 10,
  anon_sym_RBRACE = 11,
  anon_sym_LBRACE = 12,
  anon_sym_set = 13,
  anon_sym_proc = 14,
  anon_sym_elseif = 15,
  anon_sym_else = 16,
  anon_sym_if = 17,
  anon_sym_DQUOTE = 18,
  sym_escaped_character = 19,
  sym__quoted_word_content = 20,
  anon_sym_LBRACK = 21,
  anon_sym_RBRACK = 22,
  sym_source_file = 23,
  sym_commands = 24,
  aux_sym__commands = 25,
  sym__terminator = 26,
  sym__builtin = 27,
  sym_namespace = 28,
  sym__command = 29,
  sym_command = 30,
  sym_word_list = 31,
  sym__word = 32,
  sym_variable_substitution = 33,
  sym__simple_variable = 34,
  sym__braced_variable = 35,
  sym_command_block = 36,
  sym_set = 37,
  sym_procedure = 38,
  sym_procedure_arguments = 39,
  sym_elseif = 40,
  sym_else = 41,
  sym_conditional = 42,
  sym_quoted_word = 43,
  sym_braced_word = 44,
  sym_command_substitution = 45,
  aux_sym_word_list_repeat1 = 46,
  aux_sym_procedure_arguments_repeat1 = 47,
  aux_sym_conditional_repeat1 = 48,
  aux_sym_quoted_word_repeat1 = 49,
  aux_sym_braced_word_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_simple_word] = "simple_word",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [anon_sym_namespace] = "namespace",
  [anon_sym_eval] = "eval",
  [anon_sym_DOLLAR] = "$",
  [aux_sym__simple_variable_token1] = "_simple_variable_token1",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym__braced_variable_token1] = "_braced_variable_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE] = "{",
  [anon_sym_set] = "set",
  [anon_sym_proc] = "proc",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [anon_sym_if] = "if",
  [anon_sym_DQUOTE] = "\"",
  [sym_escaped_character] = "escaped_character",
  [sym__quoted_word_content] = "_quoted_word_content",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_commands] = "commands",
  [aux_sym__commands] = "_commands",
  [sym__terminator] = "_terminator",
  [sym__builtin] = "_builtin",
  [sym_namespace] = "namespace",
  [sym__command] = "_command",
  [sym_command] = "command",
  [sym_word_list] = "word_list",
  [sym__word] = "_word",
  [sym_variable_substitution] = "variable_substitution",
  [sym__simple_variable] = "_simple_variable",
  [sym__braced_variable] = "_braced_variable",
  [sym_command_block] = "command_block",
  [sym_set] = "set",
  [sym_procedure] = "procedure",
  [sym_procedure_arguments] = "procedure_arguments",
  [sym_elseif] = "elseif",
  [sym_else] = "else",
  [sym_conditional] = "conditional",
  [sym_quoted_word] = "quoted_word",
  [sym_braced_word] = "braced_word",
  [sym_command_substitution] = "command_substitution",
  [aux_sym_word_list_repeat1] = "word_list_repeat1",
  [aux_sym_procedure_arguments_repeat1] = "procedure_arguments_repeat1",
  [aux_sym_conditional_repeat1] = "conditional_repeat1",
  [aux_sym_quoted_word_repeat1] = "quoted_word_repeat1",
  [aux_sym_braced_word_repeat1] = "braced_word_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_simple_word] = sym_simple_word,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_eval] = anon_sym_eval,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym__simple_variable_token1] = aux_sym__simple_variable_token1,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym__braced_variable_token1] = aux_sym__braced_variable_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_proc] = anon_sym_proc,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_escaped_character] = sym_escaped_character,
  [sym__quoted_word_content] = sym__quoted_word_content,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_commands] = sym_commands,
  [aux_sym__commands] = aux_sym__commands,
  [sym__terminator] = sym__terminator,
  [sym__builtin] = sym__builtin,
  [sym_namespace] = sym_namespace,
  [sym__command] = sym__command,
  [sym_command] = sym_command,
  [sym_word_list] = sym_word_list,
  [sym__word] = sym__word,
  [sym_variable_substitution] = sym_variable_substitution,
  [sym__simple_variable] = sym__simple_variable,
  [sym__braced_variable] = sym__braced_variable,
  [sym_command_block] = sym_command_block,
  [sym_set] = sym_set,
  [sym_procedure] = sym_procedure,
  [sym_procedure_arguments] = sym_procedure_arguments,
  [sym_elseif] = sym_elseif,
  [sym_else] = sym_else,
  [sym_conditional] = sym_conditional,
  [sym_quoted_word] = sym_quoted_word,
  [sym_braced_word] = sym_braced_word,
  [sym_command_substitution] = sym_command_substitution,
  [aux_sym_word_list_repeat1] = aux_sym_word_list_repeat1,
  [aux_sym_procedure_arguments_repeat1] = aux_sym_procedure_arguments_repeat1,
  [aux_sym_conditional_repeat1] = aux_sym_conditional_repeat1,
  [aux_sym_quoted_word_repeat1] = aux_sym_quoted_word_repeat1,
  [aux_sym_braced_word_repeat1] = aux_sym_braced_word_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_simple_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_eval] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__simple_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__braced_variable_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_proc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_escaped_character] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_word_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_commands] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__commands] = {
    .visible = false,
    .named = false,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [sym__builtin] = {
    .visible = false,
    .named = true,
  },
  [sym_namespace] = {
    .visible = true,
    .named = true,
  },
  [sym__command] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_word_list] = {
    .visible = true,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_variable] = {
    .visible = false,
    .named = true,
  },
  [sym__braced_variable] = {
    .visible = false,
    .named = true,
  },
  [sym_command_block] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif] = {
    .visible = true,
    .named = true,
  },
  [sym_else] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_word] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_word] = {
    .visible = true,
    .named = true,
  },
  [sym_command_substitution] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_word_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_procedure_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conditional_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_word_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_body = 2,
  field_condition = 3,
  field_name = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_arguments, 1},
    {field_name, 0},
  [3] =
    {field_condition, 1},
  [4] =
    {field_arguments, 2},
    {field_body, 3},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 8,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 13,
  [18] = 18,
  [19] = 18,
  [20] = 12,
  [21] = 15,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 27,
  [30] = 30,
  [31] = 31,
  [32] = 30,
  [33] = 24,
  [34] = 31,
  [35] = 26,
  [36] = 36,
  [37] = 37,
  [38] = 36,
  [39] = 39,
  [40] = 39,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 42,
  [49] = 49,
  [50] = 41,
  [51] = 43,
  [52] = 44,
  [53] = 45,
  [54] = 54,
  [55] = 46,
  [56] = 47,
  [57] = 46,
  [58] = 42,
  [59] = 54,
  [60] = 49,
  [61] = 61,
  [62] = 47,
  [63] = 44,
  [64] = 61,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 67,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 65,
  [74] = 74,
  [75] = 70,
  [76] = 76,
  [77] = 76,
  [78] = 66,
  [79] = 71,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 86,
  [91] = 91,
  [92] = 81,
  [93] = 93,
  [94] = 94,
  [95] = 87,
  [96] = 96,
  [97] = 85,
  [98] = 98,
  [99] = 99,
  [100] = 82,
  [101] = 101,
  [102] = 102,
  [103] = 94,
  [104] = 98,
  [105] = 102,
  [106] = 96,
  [107] = 83,
  [108] = 101,
  [109] = 99,
  [110] = 98,
  [111] = 111,
  [112] = 88,
  [113] = 89,
  [114] = 99,
  [115] = 115,
  [116] = 80,
  [117] = 117,
  [118] = 111,
  [119] = 111,
  [120] = 115,
  [121] = 101,
};

static inline bool sym_comment_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || c == '"'))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym_simple_word_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '"'
        ? c == ' '
        : c <= '"')))
    : (c <= '$' || (c < '{'
      ? (c < '['
        ? c == ';'
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '$') ADVANCE(14);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']') ADVANCE(27);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (sym_comment_character_set_1(lookahead)) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__simple_variable_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__braced_variable_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym__braced_variable_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_escaped_character);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__quoted_word_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_simple_word);
      if (!sym_simple_word_character_set_1(lookahead)) ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 's') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'v') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'f') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_eval);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_proc);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 8},
  [77] = {.lex_state = 8},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 8},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 8},
  [83] = {.lex_state = 8},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 8},
  [89] = {.lex_state = 8},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 8},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 8},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 4},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 5},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 3},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 5},
  [119] = {.lex_state = 5},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_simple_word] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_eval] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_proc] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escaped_character] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(117),
    [aux_sym__commands] = STATE(4),
    [sym__terminator] = STATE(4),
    [sym__builtin] = STATE(77),
    [sym_namespace] = STATE(77),
    [sym__command] = STATE(77),
    [sym_command] = STATE(77),
    [sym__word] = STATE(11),
    [sym_variable_substitution] = STATE(11),
    [sym__simple_variable] = STATE(47),
    [sym__braced_variable] = STATE(47),
    [sym_set] = STATE(77),
    [sym_procedure] = STATE(77),
    [sym_conditional] = STATE(77),
    [sym_quoted_word] = STATE(11),
    [sym_braced_word] = STATE(11),
    [sym_command_substitution] = STATE(11),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [anon_sym_namespace] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_set] = ACTIONS(19),
    [anon_sym_proc] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [2] = {
    [sym_commands] = STATE(102),
    [aux_sym__commands] = STATE(5),
    [sym__terminator] = STATE(5),
    [sym__builtin] = STATE(76),
    [sym_namespace] = STATE(76),
    [sym__command] = STATE(76),
    [sym_command] = STATE(76),
    [sym__word] = STATE(11),
    [sym_variable_substitution] = STATE(11),
    [sym__simple_variable] = STATE(47),
    [sym__braced_variable] = STATE(47),
    [sym_set] = STATE(76),
    [sym_procedure] = STATE(76),
    [sym_conditional] = STATE(76),
    [sym_quoted_word] = STATE(11),
    [sym_braced_word] = STATE(11),
    [sym_command_substitution] = STATE(11),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(31),
    [sym_comment] = ACTIONS(33),
    [anon_sym_namespace] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_set] = ACTIONS(19),
    [anon_sym_proc] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [3] = {
    [sym_commands] = STATE(105),
    [aux_sym__commands] = STATE(5),
    [sym__terminator] = STATE(5),
    [sym__builtin] = STATE(76),
    [sym_namespace] = STATE(76),
    [sym__command] = STATE(76),
    [sym_command] = STATE(76),
    [sym__word] = STATE(11),
    [sym_variable_substitution] = STATE(11),
    [sym__simple_variable] = STATE(47),
    [sym__braced_variable] = STATE(47),
    [sym_set] = STATE(76),
    [sym_procedure] = STATE(76),
    [sym_conditional] = STATE(76),
    [sym_quoted_word] = STATE(11),
    [sym_braced_word] = STATE(11),
    [sym_command_substitution] = STATE(11),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(31),
    [sym_comment] = ACTIONS(33),
    [anon_sym_namespace] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_set] = ACTIONS(19),
    [anon_sym_proc] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [4] = {
    [aux_sym__commands] = STATE(7),
    [sym__terminator] = STATE(7),
    [sym__builtin] = STATE(77),
    [sym_namespace] = STATE(77),
    [sym__command] = STATE(77),
    [sym_command] = STATE(77),
    [sym__word] = STATE(11),
    [sym_variable_substitution] = STATE(11),
    [sym__simple_variable] = STATE(47),
    [sym__braced_variable] = STATE(47),
    [sym_set] = STATE(77),
    [sym_procedure] = STATE(77),
    [sym_conditional] = STATE(77),
    [sym_quoted_word] = STATE(11),
    [sym_braced_word] = STATE(11),
    [sym_command_substitution] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(41),
    [anon_sym_SEMI] = ACTIONS(43),
    [sym_comment] = ACTIONS(9),
    [anon_sym_namespace] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_set] = ACTIONS(19),
    [anon_sym_proc] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [5] = {
    [aux_sym__commands] = STATE(6),
    [sym__terminator] = STATE(6),
    [sym__builtin] = STATE(76),
    [sym_namespace] = STATE(76),
    [sym__command] = STATE(76),
    [sym_command] = STATE(76),
    [sym__word] = STATE(11),
    [sym_variable_substitution] = STATE(11),
    [sym__simple_variable] = STATE(47),
    [sym__braced_variable] = STATE(47),
    [sym_set] = STATE(76),
    [sym_procedure] = STATE(76),
    [sym_conditional] = STATE(76),
    [sym_quoted_word] = STATE(11),
    [sym_braced_word] = STATE(11),
    [sym_command_substitution] = STATE(11),
    [sym_simple_word] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(45),
    [anon_sym_SEMI] = ACTIONS(47),
    [sym_comment] = ACTIONS(33),
    [anon_sym_namespace] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_set] = ACTIONS(19),
    [anon_sym_proc] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [6] = {
    [aux_sym__commands] = STATE(6),
    [sym__terminator] = STATE(6),
    [sym__builtin] = STATE(76),
    [sym_namespace] = STATE(76),
    [sym__command] = STATE(76),
    [sym_command] = STATE(76),
    [sym__word] = STATE(11),
    [sym_variable_substitution] = STATE(11),
    [sym__simple_variable] = STATE(47),
    [sym__braced_variable] = STATE(47),
    [sym_set] = STATE(76),
    [sym_procedure] = STATE(76),
    [sym_conditional] = STATE(76),
    [sym_quoted_word] = STATE(11),
    [sym_braced_word] = STATE(11),
    [sym_command_substitution] = STATE(11),
    [sym_simple_word] = ACTIONS(51),
    [anon_sym_LF] = ACTIONS(54),
    [anon_sym_SEMI] = ACTIONS(57),
    [sym_comment] = ACTIONS(60),
    [anon_sym_namespace] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(66),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_set] = ACTIONS(77),
    [anon_sym_proc] = ACTIONS(80),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(89),
  },
  [7] = {
    [aux_sym__commands] = STATE(7),
    [sym__terminator] = STATE(7),
    [sym__builtin] = STATE(77),
    [sym_namespace] = STATE(77),
    [sym__command] = STATE(77),
    [sym_command] = STATE(77),
    [sym__word] = STATE(11),
    [sym_variable_substitution] = STATE(11),
    [sym__simple_variable] = STATE(47),
    [sym__braced_variable] = STATE(47),
    [sym_set] = STATE(77),
    [sym_procedure] = STATE(77),
    [sym_conditional] = STATE(77),
    [sym_quoted_word] = STATE(11),
    [sym_braced_word] = STATE(11),
    [sym_command_substitution] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(92),
    [sym_simple_word] = ACTIONS(51),
    [anon_sym_LF] = ACTIONS(94),
    [anon_sym_SEMI] = ACTIONS(97),
    [sym_comment] = ACTIONS(100),
    [anon_sym_namespace] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(66),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_set] = ACTIONS(77),
    [anon_sym_proc] = ACTIONS(80),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(89),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(103), 1,
      sym_simple_word,
    ACTIONS(105), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_namespace,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(115), 1,
      anon_sym_set,
    ACTIONS(117), 1,
      anon_sym_proc,
    ACTIONS(119), 1,
      anon_sym_if,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(16), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
    STATE(110), 7,
      sym__builtin,
      sym_namespace,
      sym__command,
      sym_command,
      sym_set,
      sym_procedure,
      sym_conditional,
  [54] = 14,
    ACTIONS(103), 1,
      sym_simple_word,
    ACTIONS(107), 1,
      anon_sym_namespace,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(115), 1,
      anon_sym_set,
    ACTIONS(117), 1,
      anon_sym_proc,
    ACTIONS(119), 1,
      anon_sym_if,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(125), 1,
      sym_comment,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(16), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
    STATE(98), 7,
      sym__builtin,
      sym_namespace,
      sym__command,
      sym_command,
      sym_set,
      sym_procedure,
      sym_conditional,
  [108] = 14,
    ACTIONS(103), 1,
      sym_simple_word,
    ACTIONS(107), 1,
      anon_sym_namespace,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(115), 1,
      anon_sym_set,
    ACTIONS(117), 1,
      anon_sym_proc,
    ACTIONS(119), 1,
      anon_sym_if,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      sym_comment,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(16), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
    STATE(104), 7,
      sym__builtin,
      sym_namespace,
      sym__command,
      sym_command,
      sym_set,
      sym_procedure,
      sym_conditional,
  [162] = 11,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_simple_word,
    ACTIONS(131), 1,
      anon_sym_LF,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    STATE(94), 1,
      sym_word_list,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(12), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [202] = 10,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 1,
      sym_simple_word,
    ACTIONS(137), 1,
      anon_sym_LF,
    ACTIONS(139), 1,
      anon_sym_SEMI,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(15), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [239] = 10,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(141), 1,
      sym_simple_word,
    ACTIONS(143), 1,
      anon_sym_LF,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(19), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [276] = 10,
    ACTIONS(147), 1,
      sym_simple_word,
    ACTIONS(150), 1,
      anon_sym_LF,
    ACTIONS(153), 1,
      anon_sym_DOLLAR,
    ACTIONS(156), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(14), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [313] = 10,
    ACTIONS(170), 1,
      sym_simple_word,
    ACTIONS(173), 1,
      anon_sym_LF,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    ACTIONS(177), 1,
      anon_sym_DOLLAR,
    ACTIONS(180), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(15), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [350] = 10,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    ACTIONS(192), 1,
      sym_simple_word,
    STATE(103), 1,
      sym_word_list,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(20), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [387] = 10,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(194), 1,
      sym_simple_word,
    ACTIONS(196), 1,
      anon_sym_LF,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(18), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [424] = 10,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(200), 1,
      sym_simple_word,
    ACTIONS(202), 1,
      anon_sym_LF,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(14), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [461] = 10,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(200), 1,
      sym_simple_word,
    ACTIONS(202), 1,
      anon_sym_LF,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(14), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_braced_word_repeat1,
  [498] = 9,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    ACTIONS(208), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(21), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [532] = 9,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    ACTIONS(210), 1,
      sym_simple_word,
    ACTIONS(213), 1,
      anon_sym_DOLLAR,
    ACTIONS(216), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(219), 1,
      anon_sym_LBRACE,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    ACTIONS(225), 1,
      anon_sym_LBRACK,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(21), 6,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
      aux_sym_word_list_repeat1,
  [566] = 2,
    ACTIONS(92), 1,
      anon_sym_LF,
    ACTIONS(72), 13,
      anon_sym_SEMI,
      sym_comment,
      anon_sym_namespace,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_set,
      anon_sym_proc,
      anon_sym_if,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [585] = 2,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(72), 12,
      anon_sym_SEMI,
      sym_comment,
      anon_sym_namespace,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_set,
      anon_sym_proc,
      anon_sym_if,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [604] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(228), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(86), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [634] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(85), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [664] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(232), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(70), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [694] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(234), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(106), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [724] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(236), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(97), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [754] = 8,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(238), 1,
      sym_simple_word,
    ACTIONS(240), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_DQUOTE,
    ACTIONS(246), 1,
      anon_sym_LBRACK,
    STATE(47), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(96), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [784] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(248), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(27), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [814] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(250), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(81), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [844] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(252), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(29), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [874] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(90), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [904] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(256), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(92), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [934] = 8,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(258), 1,
      sym_simple_word,
    STATE(56), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(75), 5,
      sym__word,
      sym_variable_substitution,
      sym_quoted_word,
      sym_braced_word,
      sym_command_substitution,
  [964] = 8,
    ACTIONS(260), 1,
      anon_sym_DOLLAR,
    ACTIONS(262), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(264), 1,
      anon_sym_DQUOTE,
    ACTIONS(266), 1,
      sym_escaped_character,
    ACTIONS(268), 1,
      sym__quoted_word_content,
    ACTIONS(270), 1,
      anon_sym_LBRACK,
    STATE(62), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(37), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [992] = 8,
    ACTIONS(272), 1,
      anon_sym_DOLLAR,
    ACTIONS(275), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(278), 1,
      anon_sym_DQUOTE,
    ACTIONS(280), 1,
      sym_escaped_character,
    ACTIONS(283), 1,
      sym__quoted_word_content,
    ACTIONS(286), 1,
      anon_sym_LBRACK,
    STATE(62), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(37), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [1020] = 8,
    ACTIONS(260), 1,
      anon_sym_DOLLAR,
    ACTIONS(262), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(266), 1,
      sym_escaped_character,
    ACTIONS(268), 1,
      sym__quoted_word_content,
    ACTIONS(270), 1,
      anon_sym_LBRACK,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
    STATE(62), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(37), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [1048] = 7,
    ACTIONS(260), 1,
      anon_sym_DOLLAR,
    ACTIONS(262), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(270), 1,
      anon_sym_LBRACK,
    ACTIONS(291), 1,
      sym_escaped_character,
    ACTIONS(293), 1,
      sym__quoted_word_content,
    STATE(62), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(36), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [1073] = 7,
    ACTIONS(260), 1,
      anon_sym_DOLLAR,
    ACTIONS(262), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(270), 1,
      anon_sym_LBRACK,
    ACTIONS(295), 1,
      sym_escaped_character,
    ACTIONS(297), 1,
      sym__quoted_word_content,
    STATE(62), 2,
      sym__simple_variable,
      sym__braced_variable,
    STATE(38), 3,
      sym_variable_substitution,
      sym_command_substitution,
      aux_sym_quoted_word_repeat1,
  [1098] = 2,
    ACTIONS(301), 1,
      anon_sym_LF,
    ACTIONS(299), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [1112] = 2,
    ACTIONS(305), 1,
      anon_sym_LF,
    ACTIONS(303), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [1126] = 2,
    ACTIONS(309), 1,
      anon_sym_LF,
    ACTIONS(307), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [1140] = 2,
    ACTIONS(313), 1,
      anon_sym_LF,
    ACTIONS(311), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [1154] = 2,
    ACTIONS(317), 1,
      anon_sym_LF,
    ACTIONS(315), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [1168] = 2,
    ACTIONS(321), 1,
      anon_sym_LF,
    ACTIONS(319), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [1182] = 2,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(323), 8,
      anon_sym_SEMI,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_simple_word,
  [1196] = 2,
    ACTIONS(303), 1,
      anon_sym_DOLLAR,
    ACTIONS(305), 6,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [1208] = 6,
    ACTIONS(327), 1,
      anon_sym_LF,
    ACTIONS(329), 1,
      anon_sym_SEMI,
    ACTIONS(331), 1,
      anon_sym_elseif,
    ACTIONS(333), 1,
      anon_sym_else,
    STATE(89), 1,
      sym_else,
    STATE(54), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [1228] = 2,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    ACTIONS(301), 6,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [1240] = 2,
    ACTIONS(307), 1,
      anon_sym_DOLLAR,
    ACTIONS(309), 6,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [1252] = 2,
    ACTIONS(311), 1,
      anon_sym_DOLLAR,
    ACTIONS(313), 6,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [1264] = 2,
    ACTIONS(315), 1,
      anon_sym_DOLLAR,
    ACTIONS(317), 6,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [1276] = 6,
    ACTIONS(331), 1,
      anon_sym_elseif,
    ACTIONS(333), 1,
      anon_sym_else,
    ACTIONS(335), 1,
      anon_sym_LF,
    ACTIONS(337), 1,
      anon_sym_SEMI,
    STATE(83), 1,
      sym_else,
    STATE(61), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [1296] = 2,
    ACTIONS(319), 1,
      anon_sym_DOLLAR,
    ACTIONS(321), 6,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [1308] = 2,
    ACTIONS(323), 1,
      anon_sym_DOLLAR,
    ACTIONS(325), 6,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_simple_word,
  [1320] = 2,
    ACTIONS(321), 1,
      sym__quoted_word_content,
    ACTIONS(319), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [1331] = 2,
    ACTIONS(305), 1,
      sym__quoted_word_content,
    ACTIONS(303), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [1342] = 5,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
    ACTIONS(339), 1,
      anon_sym_elseif,
    ACTIONS(341), 1,
      anon_sym_else,
    STATE(107), 1,
      sym_else,
    STATE(64), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [1359] = 5,
    ACTIONS(327), 1,
      anon_sym_RBRACK,
    ACTIONS(339), 1,
      anon_sym_elseif,
    ACTIONS(341), 1,
      anon_sym_else,
    STATE(113), 1,
      sym_else,
    STATE(59), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [1376] = 4,
    ACTIONS(343), 1,
      anon_sym_LF,
    ACTIONS(347), 1,
      anon_sym_elseif,
    ACTIONS(345), 2,
      anon_sym_SEMI,
      anon_sym_else,
    STATE(61), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [1391] = 2,
    ACTIONS(325), 1,
      sym__quoted_word_content,
    ACTIONS(323), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [1402] = 2,
    ACTIONS(313), 1,
      sym__quoted_word_content,
    ACTIONS(311), 5,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      sym_escaped_character,
      anon_sym_LBRACK,
  [1413] = 4,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
    ACTIONS(345), 1,
      anon_sym_else,
    ACTIONS(350), 1,
      anon_sym_elseif,
    STATE(64), 2,
      sym_elseif,
      aux_sym_conditional_repeat1,
  [1427] = 2,
    ACTIONS(353), 1,
      anon_sym_LF,
    ACTIONS(355), 3,
      anon_sym_SEMI,
      anon_sym_elseif,
      anon_sym_else,
  [1436] = 2,
    ACTIONS(357), 1,
      anon_sym_LF,
    ACTIONS(359), 3,
      anon_sym_SEMI,
      anon_sym_elseif,
      anon_sym_else,
  [1445] = 2,
    ACTIONS(361), 1,
      anon_sym_LF,
    ACTIONS(363), 3,
      anon_sym_SEMI,
      anon_sym_elseif,
      anon_sym_else,
  [1454] = 3,
    ACTIONS(365), 1,
      sym_simple_word,
    ACTIONS(367), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      aux_sym_procedure_arguments_repeat1,
  [1464] = 2,
    ACTIONS(363), 1,
      anon_sym_else,
    ACTIONS(361), 2,
      anon_sym_elseif,
      anon_sym_RBRACK,
  [1472] = 3,
    ACTIONS(369), 1,
      sym_simple_word,
    ACTIONS(371), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_procedure_arguments,
  [1482] = 3,
    ACTIONS(373), 1,
      sym_simple_word,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    STATE(116), 1,
      sym_command_block,
  [1492] = 3,
    ACTIONS(377), 1,
      sym_simple_word,
    ACTIONS(380), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_procedure_arguments_repeat1,
  [1502] = 2,
    ACTIONS(355), 1,
      anon_sym_else,
    ACTIONS(353), 2,
      anon_sym_elseif,
      anon_sym_RBRACK,
  [1510] = 3,
    ACTIONS(382), 1,
      sym_simple_word,
    ACTIONS(384), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_procedure_arguments_repeat1,
  [1520] = 3,
    ACTIONS(369), 1,
      sym_simple_word,
    ACTIONS(371), 1,
      anon_sym_LBRACE,
    STATE(79), 1,
      sym_procedure_arguments,
  [1530] = 3,
    ACTIONS(386), 1,
      anon_sym_LF,
    ACTIONS(388), 1,
      anon_sym_SEMI,
    STATE(22), 1,
      sym__terminator,
  [1540] = 3,
    ACTIONS(390), 1,
      anon_sym_LF,
    ACTIONS(392), 1,
      anon_sym_SEMI,
    STATE(23), 1,
      sym__terminator,
  [1550] = 2,
    ACTIONS(359), 1,
      anon_sym_else,
    ACTIONS(357), 2,
      anon_sym_elseif,
      anon_sym_RBRACK,
  [1558] = 3,
    ACTIONS(394), 1,
      sym_simple_word,
    ACTIONS(396), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_command_block,
  [1568] = 2,
    ACTIONS(398), 1,
      anon_sym_LF,
    ACTIONS(400), 1,
      anon_sym_SEMI,
  [1575] = 2,
    ACTIONS(396), 1,
      anon_sym_LBRACE,
    STATE(82), 1,
      sym_command_block,
  [1582] = 2,
    ACTIONS(402), 1,
      anon_sym_LF,
    ACTIONS(404), 1,
      anon_sym_SEMI,
  [1589] = 2,
    ACTIONS(406), 1,
      anon_sym_LF,
    ACTIONS(408), 1,
      anon_sym_SEMI,
  [1596] = 1,
    ACTIONS(410), 2,
      anon_sym_LBRACE,
      sym_simple_word,
  [1601] = 2,
    ACTIONS(396), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_command_block,
  [1608] = 2,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_command_block,
  [1615] = 2,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    STATE(112), 1,
      sym_command_block,
  [1622] = 2,
    ACTIONS(412), 1,
      anon_sym_LF,
    ACTIONS(414), 1,
      anon_sym_SEMI,
  [1629] = 2,
    ACTIONS(335), 1,
      anon_sym_LF,
    ACTIONS(337), 1,
      anon_sym_SEMI,
  [1636] = 2,
    ACTIONS(396), 1,
      anon_sym_LBRACE,
    STATE(65), 1,
      sym_command_block,
  [1643] = 1,
    ACTIONS(416), 2,
      anon_sym_LBRACE,
      sym_simple_word,
  [1648] = 2,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    STATE(100), 1,
      sym_command_block,
  [1655] = 1,
    ACTIONS(418), 2,
      anon_sym_LBRACE,
      sym_simple_word,
  [1660] = 2,
    ACTIONS(420), 1,
      anon_sym_LF,
    ACTIONS(422), 1,
      anon_sym_SEMI,
  [1667] = 2,
    ACTIONS(396), 1,
      anon_sym_LBRACE,
    STATE(88), 1,
      sym_command_block,
  [1674] = 2,
    ACTIONS(424), 1,
      anon_sym_LF,
    ACTIONS(426), 1,
      anon_sym_SEMI,
  [1681] = 2,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    STATE(60), 1,
      sym_command_block,
  [1688] = 1,
    ACTIONS(428), 1,
      anon_sym_RBRACK,
  [1692] = 1,
    ACTIONS(430), 1,
      anon_sym_RBRACE,
  [1696] = 1,
    ACTIONS(402), 1,
      anon_sym_RBRACK,
  [1700] = 1,
    ACTIONS(432), 1,
      aux_sym__simple_variable_token1,
  [1704] = 1,
    ACTIONS(434), 1,
      anon_sym_RBRACE,
  [1708] = 1,
    ACTIONS(420), 1,
      anon_sym_RBRACK,
  [1712] = 1,
    ACTIONS(436), 1,
      anon_sym_RBRACK,
  [1716] = 1,
    ACTIONS(438), 1,
      anon_sym_RBRACE,
  [1720] = 1,
    ACTIONS(424), 1,
      anon_sym_RBRACK,
  [1724] = 1,
    ACTIONS(406), 1,
      anon_sym_RBRACK,
  [1728] = 1,
    ACTIONS(440), 1,
      aux_sym__simple_variable_token1,
  [1732] = 1,
    ACTIONS(442), 1,
      anon_sym_RBRACE,
  [1736] = 1,
    ACTIONS(444), 1,
      anon_sym_RBRACK,
  [1740] = 1,
    ACTIONS(446), 1,
      aux_sym__braced_variable_token1,
  [1744] = 1,
    ACTIONS(412), 1,
      anon_sym_RBRACK,
  [1748] = 1,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
  [1752] = 1,
    ACTIONS(448), 1,
      anon_sym_RBRACE,
  [1756] = 1,
    ACTIONS(450), 1,
      anon_sym_eval,
  [1760] = 1,
    ACTIONS(398), 1,
      anon_sym_RBRACK,
  [1764] = 1,
    ACTIONS(452), 1,
      ts_builtin_sym_end,
  [1768] = 1,
    ACTIONS(454), 1,
      aux_sym__braced_variable_token1,
  [1772] = 1,
    ACTIONS(456), 1,
      aux_sym__braced_variable_token1,
  [1776] = 1,
    ACTIONS(458), 1,
      anon_sym_eval,
  [1780] = 1,
    ACTIONS(460), 1,
      aux_sym__simple_variable_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 54,
  [SMALL_STATE(10)] = 108,
  [SMALL_STATE(11)] = 162,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 239,
  [SMALL_STATE(14)] = 276,
  [SMALL_STATE(15)] = 313,
  [SMALL_STATE(16)] = 350,
  [SMALL_STATE(17)] = 387,
  [SMALL_STATE(18)] = 424,
  [SMALL_STATE(19)] = 461,
  [SMALL_STATE(20)] = 498,
  [SMALL_STATE(21)] = 532,
  [SMALL_STATE(22)] = 566,
  [SMALL_STATE(23)] = 585,
  [SMALL_STATE(24)] = 604,
  [SMALL_STATE(25)] = 634,
  [SMALL_STATE(26)] = 664,
  [SMALL_STATE(27)] = 694,
  [SMALL_STATE(28)] = 724,
  [SMALL_STATE(29)] = 754,
  [SMALL_STATE(30)] = 784,
  [SMALL_STATE(31)] = 814,
  [SMALL_STATE(32)] = 844,
  [SMALL_STATE(33)] = 874,
  [SMALL_STATE(34)] = 904,
  [SMALL_STATE(35)] = 934,
  [SMALL_STATE(36)] = 964,
  [SMALL_STATE(37)] = 992,
  [SMALL_STATE(38)] = 1020,
  [SMALL_STATE(39)] = 1048,
  [SMALL_STATE(40)] = 1073,
  [SMALL_STATE(41)] = 1098,
  [SMALL_STATE(42)] = 1112,
  [SMALL_STATE(43)] = 1126,
  [SMALL_STATE(44)] = 1140,
  [SMALL_STATE(45)] = 1154,
  [SMALL_STATE(46)] = 1168,
  [SMALL_STATE(47)] = 1182,
  [SMALL_STATE(48)] = 1196,
  [SMALL_STATE(49)] = 1208,
  [SMALL_STATE(50)] = 1228,
  [SMALL_STATE(51)] = 1240,
  [SMALL_STATE(52)] = 1252,
  [SMALL_STATE(53)] = 1264,
  [SMALL_STATE(54)] = 1276,
  [SMALL_STATE(55)] = 1296,
  [SMALL_STATE(56)] = 1308,
  [SMALL_STATE(57)] = 1320,
  [SMALL_STATE(58)] = 1331,
  [SMALL_STATE(59)] = 1342,
  [SMALL_STATE(60)] = 1359,
  [SMALL_STATE(61)] = 1376,
  [SMALL_STATE(62)] = 1391,
  [SMALL_STATE(63)] = 1402,
  [SMALL_STATE(64)] = 1413,
  [SMALL_STATE(65)] = 1427,
  [SMALL_STATE(66)] = 1436,
  [SMALL_STATE(67)] = 1445,
  [SMALL_STATE(68)] = 1454,
  [SMALL_STATE(69)] = 1464,
  [SMALL_STATE(70)] = 1472,
  [SMALL_STATE(71)] = 1482,
  [SMALL_STATE(72)] = 1492,
  [SMALL_STATE(73)] = 1502,
  [SMALL_STATE(74)] = 1510,
  [SMALL_STATE(75)] = 1520,
  [SMALL_STATE(76)] = 1530,
  [SMALL_STATE(77)] = 1540,
  [SMALL_STATE(78)] = 1550,
  [SMALL_STATE(79)] = 1558,
  [SMALL_STATE(80)] = 1568,
  [SMALL_STATE(81)] = 1575,
  [SMALL_STATE(82)] = 1582,
  [SMALL_STATE(83)] = 1589,
  [SMALL_STATE(84)] = 1596,
  [SMALL_STATE(85)] = 1601,
  [SMALL_STATE(86)] = 1608,
  [SMALL_STATE(87)] = 1615,
  [SMALL_STATE(88)] = 1622,
  [SMALL_STATE(89)] = 1629,
  [SMALL_STATE(90)] = 1636,
  [SMALL_STATE(91)] = 1643,
  [SMALL_STATE(92)] = 1648,
  [SMALL_STATE(93)] = 1655,
  [SMALL_STATE(94)] = 1660,
  [SMALL_STATE(95)] = 1667,
  [SMALL_STATE(96)] = 1674,
  [SMALL_STATE(97)] = 1681,
  [SMALL_STATE(98)] = 1688,
  [SMALL_STATE(99)] = 1692,
  [SMALL_STATE(100)] = 1696,
  [SMALL_STATE(101)] = 1700,
  [SMALL_STATE(102)] = 1704,
  [SMALL_STATE(103)] = 1708,
  [SMALL_STATE(104)] = 1712,
  [SMALL_STATE(105)] = 1716,
  [SMALL_STATE(106)] = 1720,
  [SMALL_STATE(107)] = 1724,
  [SMALL_STATE(108)] = 1728,
  [SMALL_STATE(109)] = 1732,
  [SMALL_STATE(110)] = 1736,
  [SMALL_STATE(111)] = 1740,
  [SMALL_STATE(112)] = 1744,
  [SMALL_STATE(113)] = 1748,
  [SMALL_STATE(114)] = 1752,
  [SMALL_STATE(115)] = 1756,
  [SMALL_STATE(116)] = 1760,
  [SMALL_STATE(117)] = 1764,
  [SMALL_STATE(118)] = 1768,
  [SMALL_STATE(119)] = 1772,
  [SMALL_STATE(120)] = 1776,
  [SMALL_STATE(121)] = 1780,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commands, 1),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(11),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(6),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(6),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(76),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(115),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(121),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(119),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__commands, 2),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(17),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(32),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(35),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(25),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(39),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(10),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__commands, 2),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(7),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(7),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__commands, 2), SHIFT_REPEAT(77),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, .production_id = 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, .production_id = 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word_list, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word_list, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(14),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(14),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(121),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(119),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(17),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(39),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_word_repeat1, 2), SHIFT_REPEAT(10),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(15),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(121),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(119),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(17),
  [186] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(39),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(10),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(21),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(101),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(111),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(13),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(40),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_word_list_repeat1, 2), SHIFT_REPEAT(9),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [272] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(108),
  [275] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(118),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2),
  [280] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(37),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(37),
  [286] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_word_repeat1, 2), SHIFT_REPEAT(8),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_word, 3),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_word, 3),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 3),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 3),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 3),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 3),
  [311] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__braced_variable, 3),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__braced_variable, 3),
  [315] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_word, 2),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_word, 2),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_variable, 2),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_variable, 2),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_substitution, 1),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_substitution, 1),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 3, .production_id = 3),
  [329] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 3, .production_id = 3),
  [331] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [333] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 4, .production_id = 3),
  [337] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 4, .production_id = 3),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conditional_repeat1, 2),
  [345] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conditional_repeat1, 2),
  [347] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conditional_repeat1, 2), SHIFT_REPEAT(33),
  [350] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conditional_repeat1, 2), SHIFT_REPEAT(24),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elseif, 3, .production_id = 3),
  [355] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif, 3, .production_id = 3),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_block, 2),
  [359] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_block, 2),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_block, 3),
  [363] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_block, 3),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [377] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_procedure_arguments_repeat1, 2), SHIFT_REPEAT(72),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_procedure_arguments_repeat1, 2),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [388] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [392] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [398] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 4, .production_id = 4),
  [400] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure, 4, .production_id = 4),
  [402] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace, 4),
  [404] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespace, 4),
  [406] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 5, .production_id = 3),
  [408] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 5, .production_id = 3),
  [410] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_arguments, 3),
  [412] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else, 2),
  [414] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else, 2),
  [416] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_arguments, 1),
  [418] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_arguments, 2),
  [420] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, .production_id = 2),
  [422] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, .production_id = 2),
  [424] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3),
  [426] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [446] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [452] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [456] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [460] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tcl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_simple_word,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
