name: CI

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/**
      - package.json
      - package-lock.json
      - eslint.config.mjs
  pull_request:
    paths:
      - .github/workflows/**
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/**
      - package.json
      - package-lock.json
      - eslint.config.mjs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint

  test:
    name: Run tests
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/setup-action/cli@v1
      - uses: tree-sitter/parser-test-action@v2
        with:
          generate: true
          test-parser: true
          # test-node: true

  fuzz:
    name: Fuzz parser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for scanner changes
        id: scanner-changes
        run: |-
          if git diff --quiet HEAD^ -- src/scanner.c; then
            printf 'changed=false\n' >> "$GITHUB_OUTPUT"
          else
            printf 'changed=true\n' >> "$GITHUB_OUTPUT"
          fi
      - uses: tree-sitter/fuzz-action@v4
        if: steps.scanner-changes.outputs.changed == 'true'
